# Generated by Django 2.0.3 on 2018-03-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team_number',
        ),
    ]
