# Generated by Django 2.0.3 on 2018-03-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0002_remove_match_team_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pit',
            name='team_number',
        ),
    ]
