# Generated by Django 2.0.3 on 2018-03-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0003_remove_pit_team_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
    ]
