# Generated by Django 2.0.3 on 2018-03-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0005_match_saturday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='saturday',
            field=models.BooleanField(default=True),
        ),
    ]
