# Generated by Django 2.0.3 on 2018-03-31 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0006_auto_20180331_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='robot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_data', to='scout.Robot'),
        ),
    ]
